name: 15. Publish Docker Image to DockerHub
run-name: ${{ github.actor }} is running the ${{ github.workflow }}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and Push the DockerImage
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: simpleace/dell-ipmi-fan-controller:latest
